### ISSUE TITLE
Failed to activate the one-dark-ui package

### ISSUE THREAD

**Issue by xmaximin** [atom/one-dark-ui#116]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [one-dark-ui](https://github.com/atom/one-dark-ui) package, v1.1.5

### Stack Trace

Failed to activate the one-dark-ui package

```
At this.editor.displayBuffer.getVisibleRowRange is not a function

TypeError: this.editor.displayBuffer.getVisibleRowRange is not a function
    at pigments-markers.ColorBufferElement.updateMarkers (/Users/xaviermaximin/.atom/packages/pigments/lib/color-buffer-element.coffee:138:55)
    at pigments-markers.ColorBufferElement.editorConfigChanged (/Users/xaviermaximin/.atom/packages/pigments/lib/color-buffer-element.coffee:113:6)
    at /Users/xaviermaximin/.atom/packages/pigments/lib/color-buffer-element.coffee:77:8
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at StyleManager.module.exports.StyleManager.addStyleElement (/Applications/Atom.app/Contents/Resources/app.asar/src/style-manager.js:114:27)
    at StyleManager.module.exports.StyleManager.addStyleSheet (/Applications/Atom.app/Contents/Resources/app.asar/src/style-manager.js:83:14)
    at ThemePackage.module.exports.Package.activateStylesheets (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:58)
    at ThemePackage.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/theme-package.js:45:28
    at ThemePackage.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/theme-package.js:41:24
    at ThemePackage.module.exports.ThemePackage.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-package.js:37:97)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:517:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:332:52
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:607:16
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:624:20
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:809:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:601:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at ThemesPanel.module.exports.ThemesPanel.updateThemeConfig (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/themes-panel.js:495:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/themes-panel.js:502:24
```

### Commands

```
     -2:59.9.0 window:install-shell-commands (div.panels-item)
     -1:58.8.0 settings-view:install-packages-and-themes (atom-text-editor.editor.is-focused)
  9x -1:42.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jshint"
    ],
    "themes": [
      "one-dark-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
emmet, v2.3.13
file-icons, v1.6.9
language-babel, v2.7.3
minimap, v4.19.0
pigments, v0.19.5

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
See my comment over on the one-light-syntax repo.

**Comment by xmaximin** [comment]
okay thanks
